In [1]:
import chromadb

In [2]:
import pandas as pd

In [15]:
df = pd.read_csv("medium_post_titles.csv")
df

,category,title,subtitle,subtitle_truncated_flag
0,work,"""21 Conversations"" - A fun (and easy) game for...",A (new?) Icebreaker game to get your team to s...,False
1,spirituality,"""Biblical Porn"" at Mars Hill",Author and UW lecturer Jessica Johnson talks a...,False
2,lgbtqia,"""CISGENDER?! Is That A Disease?!""","Or, a primer in gender vocabulary for the curi...",False
3,equality,"""Call me Nat Love"" :Black Cowboys and the Fron...",NaN,False
4,artificial-intelligence,"""Can I Train my Model on Your Computer?""",How we waste computational resources and how t...,False
...,...,...,...,...
126413,javascript,🚀 Introducing Akita: A New State Management Pa...,Every developer knows state management is diff...,True
126414,cryptocurrency,🚀Sudden Bitcoin Price Breakout Sets New Bull T...,Short-term trend: Bullish (but overbought),False
126415,artificial-intelligence,🤖 Hack4th0n & RASA chatbot,Past week I took part in an internal Hackathon...,True
126416,artificial-intelligence,🤖AI Diary #4,Topics in this issue include deep learning app...,True
126417,history,🦉 10x curiosity — Issue #68 — The checklist re...,NaN,False

In [16]:
df = df.dropna()
df

,category,title,subtitle,subtitle_truncated_flag
0,work,"""21 Conversations"" - A fun (and easy) game for...",A (new?) Icebreaker game to get your team to s...,False
1,spirituality,"""Biblical Porn"" at Mars Hill",Author and UW lecturer Jessica Johnson talks a...,False
2,lgbtqia,"""CISGENDER?! Is That A Disease?!""","Or, a primer in gender vocabulary for the curi...",False
4,artificial-intelligence,"""Can I Train my Model on Your Computer?""",How we waste computational resources and how t...,False
5,cryptocurrency,"""Cypherpunks and Wall Street"": The Security To...",Bruce Fenton presents at the World Blockchain ...,False
...,...,...,...,...
126412,javascript,🚀 Infinite Currying in Javascript,Javascript is an interesting language with a l...,True
126413,javascript,🚀 Introducing Akita: A New State Management Pa...,Every developer knows state management is diff...,True
126414,cryptocurrency,🚀Sudden Bitcoin Price Breakout Sets New Bull T...,Short-term trend: Bullish (but overbought),False
126415,artificial-intelligence,🤖 Hack4th0n & RASA chatbot,Past week I took part in an internal Hackathon...,True
126416,artificial-intelligence,🤖AI Diary #4,Topics in this issue include deep learning app...,True

In [17]:
df = df[-df["subtitle_truncated_flag"]]
df

,category,title,subtitle,subtitle_truncated_flag
0,work,"""21 Conversations"" - A fun (and easy) game for...",A (new?) Icebreaker game to get your team to s...,False
1,spirituality,"""Biblical Porn"" at Mars Hill",Author and UW lecturer Jessica Johnson talks a...,False
2,lgbtqia,"""CISGENDER?! Is That A Disease?!""","Or, a primer in gender vocabulary for the curi...",False
4,artificial-intelligence,"""Can I Train my Model on Your Computer?""",How we waste computational resources and how t...,False
5,cryptocurrency,"""Cypherpunks and Wall Street"": The Security To...",Bruce Fenton presents at the World Blockchain ...,False
...,...,...,...,...
126401,photography,📷 My Year in Photography —What I Learned in 2018,A (Hopefully) Brief History,False
126402,history,📷 Nazi commandos captured wearing U.S. Army un...,1944,False
126404,travel,"📸 — Ubud, Bali Indonesia","Man, the wifi is brutal here —I’m so far behin...",False
126411,books,🚀 2018 in Books: Startup Science & Silicon Valley,To help you find meaningful 📚to pick up in 201...,False
126414,cryptocurrency,🚀Sudden Bitcoin Price Breakout Sets New Bull T...,Short-term trend: Bullish (but overbought),False

In [18]:
# topics_of_interest = ["data-science"]
topics_of_interest = ["artificial-intelligence", "machine-learning", "data-science"]

In [19]:
df=df[df["category"].isin(topics_of_interest)]
df

,category,title,subtitle,subtitle_truncated_flag
4,artificial-intelligence,"""Can I Train my Model on Your Computer?""",How we waste computational resources and how t...,False
289,data-science,(Robot) data scientists as a service,Automating data science with symbolic regressi...,False
448,data-science,10 Free tools to get started with Data Visuali...,Jump right into the Data Visualisation process...,False
454,data-science,10 Great Programming Projects to Improve Your ...,"Improve your skills in web development, progra...",False
487,machine-learning,10 Lessons Learned From Participating in Googl...,"Quick, Draw! Doodle Recognition Challenge was ...",False
...,...,...,...,...
125958,artificial-intelligence,“Rules as Code” Can and Should Be Done Without...,An Example from Law to Code to App,False
126197,artificial-intelligence,“WTH does a neural network even learn??” — a n...,Disclaimer: Neural networks are only very loos...,False
126234,data-science,“What Should I Watch Next?” — Exploring Movie ...,"Recommender systems. What are they, and why sh...",False
126266,data-science,“Where today?” — Planning my Singapore trip wi...,"Outlining travel plans with R, k-medoids and G...",False
126355,artificial-intelligence,“no machine is an island”,An exploration of computational imagination,False

In [20]:
df["text"]=df["title"]+df["subtitle"]
df

C:\Users\Krzyz\AppData\Local\Temp\ipykernel_37512\3210622334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"]=df["title"]+df["subtitle"]

,category,title,subtitle,subtitle_truncated_flag,text
4,artificial-intelligence,"""Can I Train my Model on Your Computer?""",How we waste computational resources and how t...,False,"""Can I Train my Model on Your Computer?""How we..."
289,data-science,(Robot) data scientists as a service,Automating data science with symbolic regressi...,False,(Robot) data scientists as a serviceAutomating...
448,data-science,10 Free tools to get started with Data Visuali...,Jump right into the Data Visualisation process...,False,10 Free tools to get started with Data Visuali...
454,data-science,10 Great Programming Projects to Improve Your ...,"Improve your skills in web development, progra...",False,10 Great Programming Projects to Improve Your ...
487,machine-learning,10 Lessons Learned From Participating in Googl...,"Quick, Draw! Doodle Recognition Challenge was ...",False,10 Lessons Learned From Participating in Googl...
...,...,...,...,...,...
125958,artificial-intelligence,“Rules as Code” Can and Should Be Done Without...,An Example from Law to Code to App,False,“Rules as Code” Can and Should Be Done Without...
126197,artificial-intelligence,“WTH does a neural network even learn??” — a n...,Disclaimer: Neural networks are only very loos...,False,“WTH does a neural network even learn??” — a n...
126234,data-science,“What Should I Watch Next?” — Exploring Movie ...,"Recommender systems. What are they, and why sh...",False,“What Should I Watch Next?” — Exploring Movie ...
126266,data-science,“Where today?” — Planning my Singapore trip wi...,"Outlining travel plans with R, k-medoids and G...",False,“Where today?” — Planning my Singapore trip wi...
126355,artificial-intelligence,“no machine is an island”,An exploration of computational imagination,False,“no machine is an island”An exploration of com...

In [21]:
df["meta"] =df.apply( lambda x: {
    "text": x["text"],
    "category": x["category"]
}, axis=1)
df

C:\Users\Krzyz\AppData\Local\Temp\ipykernel_37512\145144825.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["meta"] =df.apply( lambda x: {

,category,title,subtitle,subtitle_truncated_flag,text,meta
4,artificial-intelligence,"""Can I Train my Model on Your Computer?""",How we waste computational resources and how t...,False,"""Can I Train my Model on Your Computer?""How we...","{'text': '""Can I Train my Model on Your Comput..."
289,data-science,(Robot) data scientists as a service,Automating data science with symbolic regressi...,False,(Robot) data scientists as a serviceAutomating...,{'text': '(Robot) data scientists as a service...
448,data-science,10 Free tools to get started with Data Visuali...,Jump right into the Data Visualisation process...,False,10 Free tools to get started with Data Visuali...,{'text': '10 Free tools to get started with Da...
454,data-science,10 Great Programming Projects to Improve Your ...,"Improve your skills in web development, progra...",False,10 Great Programming Projects to Improve Your ...,{'text': '10 Great Programming Projects to Imp...
487,machine-learning,10 Lessons Learned From Participating in Googl...,"Quick, Draw! Doodle Recognition Challenge was ...",False,10 Lessons Learned From Participating in Googl...,{'text': '10 Lessons Learned From Participatin...
...,...,...,...,...,...,...
125958,artificial-intelligence,“Rules as Code” Can and Should Be Done Without...,An Example from Law to Code to App,False,“Rules as Code” Can and Should Be Done Without...,{'text': '“Rules as Code” Can and Should Be Do...
126197,artificial-intelligence,“WTH does a neural network even learn??” — a n...,Disclaimer: Neural networks are only very loos...,False,“WTH does a neural network even learn??” — a n...,{'text': '“WTH does a neural network even lear...
126234,data-science,“What Should I Watch Next?” — Exploring Movie ...,"Recommender systems. What are they, and why sh...",False,“What Should I Watch Next?” — Exploring Movie ...,{'text': '“What Should I Watch Next?” — Explor...
126266,data-science,“Where today?” — Planning my Singapore trip wi...,"Outlining travel plans with R, k-medoids and G...",False,“Where today?” — Planning my Singapore trip wi...,{'text': '“Where today?” — Planning my Singapo...
126355,artificial-intelligence,“no machine is an island”,An exploration of computational imagination,False,“no machine is an island”An exploration of com...,{'text': '“no machine is an island”An explorat...

In [22]:
df.head(2)

,category,title,subtitle,subtitle_truncated_flag,text,meta
4,artificial-intelligence,"""Can I Train my Model on Your Computer?""",How we waste computational resources and how t...,False,"""Can I Train my Model on Your Computer?""How we...","{'text': '""Can I Train my Model on Your Comput..."
289,data-science,(Robot) data scientists as a service,Automating data science with symbolic regressi...,False,(Robot) data scientists as a serviceAutomating...,{'text': '(Robot) data scientists as a service...

In [ ]:
### CHROMA DB SETUP

In [23]:
chroma_client = chromadb.Client() #no argument = in memeory db

In [24]:
#collection creation
article_collection = chroma_client.create_collection(name="medium-article")

In [25]:
df.index.tolist()

[4,
 289,
 448,
 454,
 487,
 493,
 505,
 524,
 525,
 538,
 587,
 673,
 752,
 772,
 785,
 804,
 982,
 1137,
 1389,
 1464,
 1472,
 1516,
 1588,
 1866,
 1995,
 2026,
 2028,
 2118,
 2173,
 2233,
 2347,
 2415,
 2496,
 2518,
 2581,
 2586,
 2645,
 2663,
 2810,
 2836,
 2916,
 2938,
 2981,
 3130,
 3152,
 3232,
 3257,
 3262,
 3352,
 3356,
 3370,
 3450,
 3481,
 3507,
 3510,
 3522,
 3612,
 3629,
 3658,
 3752,
 4069,
 4098,
 4099,
 4124,
 4135,
 4140,
 4154,
 4155,
 4159,
 4171,
 4179,
 4180,
 4200,
 4205,
 4210,
 4213,
 4309,
 4327,
 4552,
 4561,
 4575,
 4578,
 4579,
 4582,
 4583,
 4585,
 4590,
 4591,
 4594,
 4597,
 4639,
 4722,
 4723,
 4796,
 4797,
 4808,
 4809,
 4821,
 4830,
 4845,
 4994,
 5031,
 5089,
 5090,
 5111,
 5113,
 5114,
 5116,
 5119,
 5120,
 5123,
 5176,
 5192,
 5255,
 5401,
 5465,
 5487,
 5566,
 5581,
 5663,
 5665,
 5666,
 5755,
 5785,
 5825,
 5829,
 5847,
 5867,
 5870,
 5873,
 5936,
 5944,
 5952,
 5953,
 6038,
 6165,
 6234,
 6245,
 6280,
 6355,
 6380,
 6388,
 6480,
 6503,
 6512,
 6514,
 6517,
 6519,
 6521,
 6522,
 6524,
 6540,
 6627,
 6690,
 6725,
 6787,
 6908,
 6934,
 7134,
 7161,
 7182,
 7208,
 7221,
 7225,
 7271,
 7274,
 7284,
 7302,
 7349,
 7351,
 7352,
 7355,
 7374,
 7418,
 7476,
 7511,
 7522,
 7557,
 7594,
 7622,
 7625,
 7634,
 7657,
 7678,
 7680,
 7681,
 7693,
 7734,
 7736,
 7760,
 7776,
 7850,
 7858,
 7859,
 7866,
 7869,
 7871,
 7872,
 7873,
 7877,
 7879,
 7881,
 7884,
 7885,
 7888,
 7892,
 7925,
 7927,
 7928,
 7931,
 7933,
 7934,
 7935,
 7937,
 7938,
 7939,
 7941,
 7942,
 7946,
 7952,
 7954,
 7955,
 7956,
 7957,
 7962,
 7963,
 7964,
 7970,
 7973,
 7976,
 7977,
 7978,
 7980,
 7981,
 7982,
 7984,
 7992,
 7995,
 7997,
 7999,
 8000,
 8003,
 8005,
 8006,
 8007,
 8008,
 8011,
 8013,
 8014,
 8015,
 8016,
 8018,
 8019,
 8023,
 8024,
 8028,
 8031,
 8034,
 8036,
 8038,
 8040,
 8041,
 8042,
 8044,
 8045,
 8047,
 8049,
 8051,
 8057,
 8058,
 8059,
 8060,
 8062,
 8063,
 8064,
 8065,
 8067,
 8068,
 8070,
 8071,
 8074,
 8075,
 8078,
 8080,
 8081,
 8084,
 8090,
 8093,
 8094,
 8095,
 8097,
 8142,
 8160,
 8200,
 8317,
 8403,
 8474,
 8478,
 8479,
 8498,
 8524,
 8547,
 8559,
 8574,
 8607,
 8612,
 8669,
 8714,
 8728,
 8753,
 8754,
 8762,
 8763,
 8766,
 8767,
 8775,
 8776,
 8780,
 8785,
 8786,
 8788,
 8819,
 8827,
 8832,
 8834,
 8860,
 9195,
 9200,
 9202,
 9215,
 9216,
 9295,
 9298,
 9303,
 9310,
 9330,
 9347,
 9350,
 9353,
 9355,
 9356,
 9359,
 9363,
 9365,
 9368,
 9369,
 9390,
 9399,
 9474,
 9508,
 9534,
 9548,
 9558,
 9573,
 9576,
 9583,
 9622,
 9625,
 9649,
 9698,
 9726,
 9844,
 9853,
 9862,
 9882,
 9918,
 9929,
 9951,
 9998,
 10092,
 10251,
 10287,
 10288,
 10289,
 10290,
 10291,
 10301,
 10325,
 10331,
 10462,
 10475,
 10478,
 10499,
 10528,
 10530,
 10531,
 10585,
 10586,
 10587,
 10596,
 10599,
 10600,
 10603,
 10604,
 10608,
 10609,
 10613,
 10618,
 10629,
 10630,
 10634,
 10636,
 10656,
 10657,
 10658,
 10659,
 10660,
 10679,
 10755,
 10831,
 10845,
 10848,
 10853,
 10860,
 10937,
 10940,
 10950,
 10958,
 10961,
 10967,
 10981,
 10986,
 10987,
 10995,
 11023,
 11025,
 11026,
 11064,
 11068,
 11077,
 11078,
 11079,
 11081,
 11087,
 11088,
 11090,
 11198,
 11243,
 11265,
 11418,
 11466,
 11475,
 11476,
 11480,
 11492,
 11502,
 11514,
 11576,
 11641,
 11918,
 11920,
 11923,
 11924,
 11926,
 11933,
 11939,
 11941,
 11945,
 11953,
 11962,
 12003,
 12006,
 12013,
 12021,
 12022,
 12043,
 12151,
 12180,
 12189,
 12192,
 12450,
 12636,
 12718,
 12733,
 12741,
 12750,
 12751,
 12756,
 12758,
 12760,
 12761,
 12762,
 12763,
 12764,
 12765,
 12766,
 12768,
 12769,
 12770,
 12771,
 12772,
 12774,
 12775,
 12776,
 12777,
 12780,
 12782,
 12783,
 12785,
 12787,
 12793,
 12795,
 12797,
 12799,
 12801,
 12803,
 12804,
 12806,
 12812,
 12814,
 12816,
 12817,
 12818,
 12822,
 12824,
 12825,
 12826,
 12827,
 12828,
 12830,
 12832,
 12836,
 12841,
 12843,
 12845,
 12849,
 12852,
 12876,
 13144,
 13197,
 13198,
 13213,
 13395,
 13396,
 13404,
 13405,
 13406,
 13412,
 13413,
 13419,
 13435,
 13438,
 13444,
 13459,
 13464,
 13468,
 13485,
 13573,
 13575,
 13576,
 13581,
 13582,
 13584,
 13588,
 13589,
 13590,
 13591,
 13598,
 13607,
 13611,
 13612,
 13613,
 13614,
 13615,
 13616,
 13618,
 13630,
 13636,
 13640,
 13647,
 13656,
 13661,
 13665,
 13668,
 13682,
 13690,
 13695,
 13802,
 13807,
 13855,
 13865,
 13866,
 13867,
 13869,
 13887,
 13936,
 13951,
 13992,
 14054,
 14127,
 14186,
 14230,
 14255,
 14262,
 14286,
 14342,
 14349,
 14351,
 14356,
 14357,
 14360,
 14361,
 14362,
 14367,
 14494,
 14496,
 14572,
 14713,
 14714,
 14727,
 14759,
 14785,
 14786,
 14790,
 14797,
 14805,
 14872,
 14982,
 14995,
 15048,
 15077,
 15081,
 15148,
 15209,
 15216,
 15257,
 15260,
 15274,
 15294,
 15370,
 15374,
 15396,
 15404,
 15447,
 15448,
 15522,
 15537,
 15538,
 15539,
 15540,
 15545,
 15582,
 15587,
 15592,
 15599,
 15600,
 15613,
 15652,
 15736,
 15826,
 16183,
 16227,
 16255,
 16499,
 16506,
 16667,
 16702,
 16742,
 16753,
 16761,
 16762,
 16835,
 16925,
 17015,
 17047,
 17051,
 17094,
 17106,
 17210,
 17332,
 17350,
 17375,
 17383,
 17485,
 17536,
 17543,
 17560,
 17568,
 17589,
 17591,
 17594,
 17607,
 17641,
 17649,
 17652,
 17655,
 17663,
 17666,
 17670,
 17671,
 17673,
 17674,
 17678,
 17688,
 17691,
 17698,
 17703,
 17741,
 17742,
 17763,
 17809,
 17814,
 17832,
 17838,
 17851,
 17853,
 17854,
 17856,
 17868,
 17873,
 17884,
 17923,
 17925,
 17926,
 17936,
 17954,
 17965,
 17967,
 17968,
 17969,
 17973,
 17990,
 17991,
 17992,
 18011,
 18015,
 18016,
 18022,
 18028,
 18060,
 18061,
 18106,
 18116,
 18118,
 18257,
 18278,
 18294,
 18358,
 18451,
 18494,
 18509,
 18513,
 18514,
 18516,
 18517,
 18519,
 18583,
 18611,
 18613,
 18628,
 18637,
 18640,
 18641,
 18642,
 18643,
 18686,
 18714,
 18724,
 18726,
 18843,
 18844,
 18845,
 18846,
 18847,
 18868,
 18870,
 18900,
 18933,
 18976,
 18979,
 19065,
 19074,
 19093,
 19124,
 19201,
 19209,
 19265,
 19293,
 19376,
 19422,
 19448,
 19499,
 19525,
 19536,
 19544,
 19596,
 19633,
 19672,
 19716,
 19726,
 19768,
 19769,
 19786,
 19836,
 19837,
 19897,
 19898,
 19904,
 19907,
 19959,
 20100,
 20104,
 20107,
 20121,
 20124,
 20142,
 20287,
 20331,
 20406,
 20450,
 20458,
 20482,
 20488,
 20493,
 20496,
 20563,
 20573,
 20615,
 20658,
 20680,
 20698,
 20703,
 20706,
 20708,
 20713,
 20714,
 20719,
 20722,
 20723,
 20749,
 20756,
 20766,
 20767,
 20774,
 20779,
 20881,
 20946,
 21021,
 21023,
 21043,
 21057,
 21061,
 21095,
 21108,
 21119,
 21148,
 21152,
 21163,
 21164,
 21272,
 21273,
 21295,
 21301,
 21303,
 21304,
 21305,
 21314,
 21327,
 21361,
 21376,
 21401,
 21603,
 21610,
 21615,
 21618,
 21619,
 21623,
 21647,
 21649,
 21661,
 21669,
 21685,
 21711,
 21721,
 21730,
 21731,
 21732,
 21744,
 21745,
 21747,
 21750,
 21752,
 21756,
 21757,
 21763,
 21765,
 21787,
 21879,
 21930,
 21968,
 21998,
 22157,
 22186,
 22235,
 22236,
 22244,
 22291,
 22319,
 22325,
 22331,
 22348,
 22357,
 22365,
 22367,
 22370,
 22371,
 22373,
 22374,
 22375,
 22453,
 22500,
 22501,
 22556,
 22603,
 22665,
 22666,
 22696,
 22754,
 22823,
 22828,
 22847,
 22855,
 22863,
 22872,
 22887,
 22892,
 22919,
 22951,
 22983,
 22995,
 23031,
 23048,
 23106,
 23116,
 23135,
 23140,
 23221,
 23250,
 23272,
 23286,
 23313,
 23320,
 23400,
 23649,
 23650,
 23658,
 23681,
 23690,
 23691,
 23694,
 23701,
 23706,
 23744,
 23749,
 23750,
 23753,
 23786,
 23789,
 23825,
 23842,
 23851,
 23893,
 23989,
 24009,
 24031,
 24123,
 24126,
 24134,
 24137,
 24143,
 24150,
 24151,
 24152,
 24153,
 24155,
 24157,
 24159,
 24161,
 24162,
 24165,
 24169,
 24174,
 24196,
 24197,
 24200,
 24201,
 24205,
 24206,
 24213,
 24215,
 24218,
 24222,
 24223,
 24224,
 24227,
 24228,
 24231,
 24232,
 24234,
 24238,
 ...]

In [27]:
#inserting data
article_collection.add(
    ids=[f"{x}" for x in df.index.tolist()], # vector ids - strings
    documents=df["text"].tolist(), #each row/text in database is document
    metadatas = df["meta"].tolist()
)

C:\Users\Krzyz\.cache\chroma\onnx_models\all-MiniLM-L6-v2\onnx.tar.gz: 100%|█████| 79.3M/79.3M [00:22<00:00, 3.72MiB/s]

In [28]:
#article_collection.delete() #removing collection
#article_collection.upsert() #takie samo jak add ale tutaj dodaje i update'uje jezeli jest zmiana

In [29]:
#vector query
qry_str =  "best data science library?"

In [31]:
article_collection.query(query_texts=qry_str, n_results=1) #n_result means how many results we get

{'ids': [['65427']],
 'distances': [[0.6087137460708618]],
 'metadatas': [[{'category': 'data-science',
    'text': 'My Favorite Data Science/Machine Learning ResourcesA summary of sources to get into Data Science'}]],
 'embeddings': None,
 'documents': [['My Favorite Data Science/Machine Learning ResourcesA summary of sources to get into Data Science']],
 'uris': None,
 'data': None}

In [33]:
qry_str2 = "best data ai library?"

In [34]:
article_collection.query(query_texts=qry_str2, n_results=2)

{'ids': [['103719', '24137']],
 'distances': [[0.6297023296356201, 0.7120206356048584]],
 'metadatas': [[{'category': 'machine-learning',
    'text': 'Top 7 libraries and packages of the year for Data Science and AI: Python & RThis is a list of the best libraries and packages that changed our lives this year, compiled from my weekly digests'},
   {'category': 'artificial-intelligence',
    'text': 'Data Commons Version 1.0: A Framework to Build Toward AI for GoodA roadmap for data from the 2018 AI for Good Summit'}]],
 'embeddings': None,
 'documents': [['Top 7 libraries and packages of the year for Data Science and AI: Python & RThis is a list of the best libraries and packages that changed our lives this year, compiled from my weekly digests',
   'Data Commons Version 1.0: A Framework to Build Toward AI for GoodA roadmap for data from the 2018 AI for Good Summit']],
 'uris': None,
 'data': None}

In [35]:
# tunning chroma db with custom setting
from chromadb.config import Settings

In [38]:
chroma_client2 = chromadb.Client(Settings(
    persist_directory="medium-chroma-db", #place where db will be saved in current working directory
    chroma_db_impl="duckdb-parquet" #default value
))
article_collection.delete()
article_collection = chroma_client2.create_collection(name="medium_article")

ValueError: An instance of Chroma already exists for ephemeral with different settings

In [ ]:
}