In [1]:
import chromadb

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("medium_post_titles.csv")
df

,category,title,subtitle,subtitle_truncated_flag
0,work,"""21 Conversations"" - A fun (and easy) game for...",A (new?) Icebreaker game to get your team to s...,False
1,spirituality,"""Biblical Porn"" at Mars Hill",Author and UW lecturer Jessica Johnson talks a...,False
2,lgbtqia,"""CISGENDER?! Is That A Disease?!""","Or, a primer in gender vocabulary for the curi...",False
3,equality,"""Call me Nat Love"" :Black Cowboys and the Fron...",NaN,False
4,artificial-intelligence,"""Can I Train my Model on Your Computer?""",How we waste computational resources and how t...,False
...,...,...,...,...
126413,javascript,🚀 Introducing Akita: A New State Management Pa...,Every developer knows state management is diff...,True
126414,cryptocurrency,🚀Sudden Bitcoin Price Breakout Sets New Bull T...,Short-term trend: Bullish (but overbought),False
126415,artificial-intelligence,🤖 Hack4th0n & RASA chatbot,Past week I took part in an internal Hackathon...,True
126416,artificial-intelligence,🤖AI Diary #4,Topics in this issue include deep learning app...,True
126417,history,🦉 10x curiosity — Issue #68 — The checklist re...,NaN,False

In [6]:
df = df.dropna()
df

,category,title,subtitle,subtitle_truncated_flag
0,work,"""21 Conversations"" - A fun (and easy) game for...",A (new?) Icebreaker game to get your team to s...,False
1,spirituality,"""Biblical Porn"" at Mars Hill",Author and UW lecturer Jessica Johnson talks a...,False
2,lgbtqia,"""CISGENDER?! Is That A Disease?!""","Or, a primer in gender vocabulary for the curi...",False
4,artificial-intelligence,"""Can I Train my Model on Your Computer?""",How we waste computational resources and how t...,False
5,cryptocurrency,"""Cypherpunks and Wall Street"": The Security To...",Bruce Fenton presents at the World Blockchain ...,False
...,...,...,...,...
126412,javascript,🚀 Infinite Currying in Javascript,Javascript is an interesting language with a l...,True
126413,javascript,🚀 Introducing Akita: A New State Management Pa...,Every developer knows state management is diff...,True
126414,cryptocurrency,🚀Sudden Bitcoin Price Breakout Sets New Bull T...,Short-term trend: Bullish (but overbought),False
126415,artificial-intelligence,🤖 Hack4th0n & RASA chatbot,Past week I took part in an internal Hackathon...,True
126416,artificial-intelligence,🤖AI Diary #4,Topics in this issue include deep learning app...,True

In [7]:
df = df[-df["subtitle_truncated_flag"]]
df

,category,title,subtitle,subtitle_truncated_flag
0,work,"""21 Conversations"" - A fun (and easy) game for...",A (new?) Icebreaker game to get your team to s...,False
1,spirituality,"""Biblical Porn"" at Mars Hill",Author and UW lecturer Jessica Johnson talks a...,False
2,lgbtqia,"""CISGENDER?! Is That A Disease?!""","Or, a primer in gender vocabulary for the curi...",False
4,artificial-intelligence,"""Can I Train my Model on Your Computer?""",How we waste computational resources and how t...,False
5,cryptocurrency,"""Cypherpunks and Wall Street"": The Security To...",Bruce Fenton presents at the World Blockchain ...,False
...,...,...,...,...
126401,photography,📷 My Year in Photography —What I Learned in 2018,A (Hopefully) Brief History,False
126402,history,📷 Nazi commandos captured wearing U.S. Army un...,1944,False
126404,travel,"📸 — Ubud, Bali Indonesia","Man, the wifi is brutal here —I’m so far behin...",False
126411,books,🚀 2018 in Books: Startup Science & Silicon Valley,To help you find meaningful 📚to pick up in 201...,False
126414,cryptocurrency,🚀Sudden Bitcoin Price Breakout Sets New Bull T...,Short-term trend: Bullish (but overbought),False

In [8]:
topics_of_interest = ["data-science"]

In [9]:
df=df[df["category"].isin(topics_of_interest)]
df

,category,title,subtitle,subtitle_truncated_flag
289,data-science,(Robot) data scientists as a service,Automating data science with symbolic regressi...,False
448,data-science,10 Free tools to get started with Data Visuali...,Jump right into the Data Visualisation process...,False
454,data-science,10 Great Programming Projects to Improve Your ...,"Improve your skills in web development, progra...",False
493,data-science,10 Machine Learning Methods that Every Data Sc...,Jump-start your data science skills,False
524,data-science,10 Python Pandas tricks that make your work mo...,Some commands you may know already but may no...,False
...,...,...,...,...
124139,data-science,Zalando Dress Recomendation and Tagging,Utilize images and textual descriptions to sug...,False
124258,data-science,[NLP] Performance of Different Word Embeddings...,"compared among word2vec, TF-IDF weighted, GloV...",False
124396,data-science,hompson Sampling For Multi-Armed Bandit Proble...,Using Bayesian Updating For Online Decision Ma...,False
126234,data-science,“What Should I Watch Next?” — Exploring Movie ...,"Recommender systems. What are they, and why sh...",False
126266,data-science,“Where today?” — Planning my Singapore trip wi...,"Outlining travel plans with R, k-medoids and G...",False

In [10]:
df["text"]=df["title"]+df["subtitle"]
df

C:\Users\Krzyz\AppData\Local\Temp\ipykernel_37512\3210622334.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"]=df["title"]+df["subtitle"]

,category,title,subtitle,subtitle_truncated_flag,text
289,data-science,(Robot) data scientists as a service,Automating data science with symbolic regressi...,False,(Robot) data scientists as a serviceAutomating...
448,data-science,10 Free tools to get started with Data Visuali...,Jump right into the Data Visualisation process...,False,10 Free tools to get started with Data Visuali...
454,data-science,10 Great Programming Projects to Improve Your ...,"Improve your skills in web development, progra...",False,10 Great Programming Projects to Improve Your ...
493,data-science,10 Machine Learning Methods that Every Data Sc...,Jump-start your data science skills,False,10 Machine Learning Methods that Every Data Sc...
524,data-science,10 Python Pandas tricks that make your work mo...,Some commands you may know already but may no...,False,10 Python Pandas tricks that make your work mo...
...,...,...,...,...,...
124139,data-science,Zalando Dress Recomendation and Tagging,Utilize images and textual descriptions to sug...,False,Zalando Dress Recomendation and TaggingUtilize...
124258,data-science,[NLP] Performance of Different Word Embeddings...,"compared among word2vec, TF-IDF weighted, GloV...",False,[NLP] Performance of Different Word Embeddings...
124396,data-science,hompson Sampling For Multi-Armed Bandit Proble...,Using Bayesian Updating For Online Decision Ma...,False,hompson Sampling For Multi-Armed Bandit Proble...
126234,data-science,“What Should I Watch Next?” — Exploring Movie ...,"Recommender systems. What are they, and why sh...",False,“What Should I Watch Next?” — Exploring Movie ...
126266,data-science,“Where today?” — Planning my Singapore trip wi...,"Outlining travel plans with R, k-medoids and G...",False,“Where today?” — Planning my Singapore trip wi...

In [14]:
df["meta"] =df.apply( lambda x: {
    "text": x["text"],
    "category": x["category"]
}, axis=1)
df

C:\Users\Krzyz\AppData\Local\Temp\ipykernel_37512\145144825.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["meta"] =df.apply( lambda x: {

,category,title,subtitle,subtitle_truncated_flag,text,meta
289,data-science,(Robot) data scientists as a service,Automating data science with symbolic regressi...,False,(Robot) data scientists as a serviceAutomating...,{'text': '(Robot) data scientists as a service...
448,data-science,10 Free tools to get started with Data Visuali...,Jump right into the Data Visualisation process...,False,10 Free tools to get started with Data Visuali...,{'text': '10 Free tools to get started with Da...
454,data-science,10 Great Programming Projects to Improve Your ...,"Improve your skills in web development, progra...",False,10 Great Programming Projects to Improve Your ...,{'text': '10 Great Programming Projects to Imp...
493,data-science,10 Machine Learning Methods that Every Data Sc...,Jump-start your data science skills,False,10 Machine Learning Methods that Every Data Sc...,{'text': '10 Machine Learning Methods that Eve...
524,data-science,10 Python Pandas tricks that make your work mo...,Some commands you may know already but may no...,False,10 Python Pandas tricks that make your work mo...,{'text': '10 Python Pandas tricks that make yo...
...,...,...,...,...,...,...
124139,data-science,Zalando Dress Recomendation and Tagging,Utilize images and textual descriptions to sug...,False,Zalando Dress Recomendation and TaggingUtilize...,{'text': 'Zalando Dress Recomendation and Tagg...
124258,data-science,[NLP] Performance of Different Word Embeddings...,"compared among word2vec, TF-IDF weighted, GloV...",False,[NLP] Performance of Different Word Embeddings...,{'text': '[NLP] Performance of Different Word ...
124396,data-science,hompson Sampling For Multi-Armed Bandit Proble...,Using Bayesian Updating For Online Decision Ma...,False,hompson Sampling For Multi-Armed Bandit Proble...,{'text': 'hompson Sampling For Multi-Armed Ban...
126234,data-science,“What Should I Watch Next?” — Exploring Movie ...,"Recommender systems. What are they, and why sh...",False,“What Should I Watch Next?” — Exploring Movie ...,{'text': '“What Should I Watch Next?” — Explor...
126266,data-science,“Where today?” — Planning my Singapore trip wi...,"Outlining travel plans with R, k-medoids and G...",False,“Where today?” — Planning my Singapore trip wi...,{'text': '“Where today?” — Planning my Singapo...